import "../styles/globals.css";
import type { AppProps } from "next/app";
import { ApolloProvider, ApolloClient, InMemoryCache } from "@apollo/client";
import Head from "next/head";
import Image from "next/image";
import logo from "../public/images/thirdweb.png";

const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: "/api",
});

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ApolloProvider client={client}>
      <div className="max-w-full flex min-h-screen w-full flex-col items-center overflow-hidden bg-grey-1000 min-w-screen">
        <Head>
          <title>Who&apos;s #1?</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="w-full border-b border-gray-600 h-24 flex flex-row justify-between">
          <div className="flex flex-row justify-start ml-8">
            <div className="m-auto h-20 aspect-square"><Image src={logo} alt="101 Logo" height="80" width="80" /></div>
            <div className="m-auto">
              <p className="text-s text-white">101</p>
              <p className="text-s text-white opacity-50">101.xyz</p>
            </div>
          </div>
          <div></div>
        </div>
        <Component {...pageProps} />
      </div>
    </ApolloProvider>
  );
}

export default MyApp;
